### PR TITLE
Upgrading to current atom API

### LINKED ISSUE #6: Uncaught TypeError: Cannot read property 'length' of undefined
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [copy-with-style](https://github.com/my-codeworks/copy-with-style) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Akira\.atom\packages\copy-with-style\lib\atom_editor.js:21

TypeError: Cannot read property 'length' of undefined
    at /packages/copy-with-style/lib/atom_editor.js:21:53)
    at HTMLgenerator.generate (/packages/copy-with-style/lib/html_generator.js:58:5)
    at Object.copy (/packages/copy-with-style/lib/main.js:58:68)
    at HTMLElement.copyWithStylePreset1 (/packages/copy-with-style/lib/main.js:19:45)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at SelectListView.didClickItem (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/atom-select-list/src/select-list-view.js:228:16)
    at ListItemView.onclick (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/atom-select-list/src/select-list-view.js:168:37)
    at ListItemView.didClick (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/atom-select-list/src/select-list-view.js:361:16)
```

### Commands

```
     -3:52.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -1:19.2.0 command-palette:toggle (input.hidden-input)
  3x -1:15 core:backspace (input.hidden-input)
  2x -1:12.8.0 core:move-down (input.hidden-input)
     -1:10.6.0 copy-with-style:preset1 (input.hidden-input)
     -1:03.6.0 application:open-folder (input.hidden-input)
     -0:52.4.0 application:open-file (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-clock 0.1.13 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
copy-with-style 1.1.0 
file-icons 2.1.10 
highlight-selected 0.13.1 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
monokai 0.24.0 
simplified-chinese-menu 5.3.4 
sync-settings 0.8.2 
tortoise-svn 0.5.1 
tree-view-finder 0.2.1 
```

### LINKED ISSUE #8: Uncaught TypeError: Cannot read property 'length' of undefined
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 ia32
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [copy-with-style](https://github.com/my-codeworks/copy-with-style) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Administrator\.atom\packages\copy-with-style\lib\atom_editor.js:21

TypeError: Cannot read property 'length' of undefined
    at /packages/copy-with-style/lib/atom_editor.js:21:53)
    at HTMLgenerator.generate (/packages/copy-with-style/lib/html_generator.js:58:5)
    at Object.copy (/packages/copy-with-style/lib/main.js:58:68)
    at HTMLElement.copyWithStylePreset1 (/packages/copy-with-style/lib/main.js:19:45)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/command-registry.js:381:36)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/command-palette/lib/command-palette-view.js:144:35)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at SelectListView.didClickItem (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:242:16)
    at ListItemView.onclick (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:181:39)
    at ListItemView.didClick (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:375:16)
```

### Commands

```
     -6:50.1.0 copy-as-rtf:copy (span.syntax--meta.syntax--function-call.syntax--arguments.syntax--python)
     -5:23.4.0 core:save (input.hidden-input)
     -5:13.3.0 copy-as-rtf:copy (div.line)
     -3:21.5.0 core:copy (input.hidden-input)
     -3:19.9.0 editor:copy-path (input.hidden-input)
  7x -3:11 core:backspace (input.hidden-input)
     -1:56.9.0 command-palette:toggle (input.hidden-input)
     -1:47.7.0 copy-with-style:preset1 (input.hidden-input)
     -1:12.4.0 command-palette:toggle (input.hidden-input)
     -1:03.3.0 pane:show-item-1 (input.hidden-input)
  6x -1:01.7.0 core:backspace (input.hidden-input)
     -0:59.4.0 copy-with-style:preset1 (input.hidden-input)
     -0:14.9.0 command-palette:toggle (input.hidden-input)
     -0:10.8.0 copy-with-style:preset2 (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.5 
copy-as-rtf 0.9.3 
copy-with-style 1.1.0 
file-icons 2.1.14 
highlight-selected 0.13.1 
simplified-chinese-menu 5.3.5 
```

### LINKED ISSUE #13: Uncaught TypeError: Cannot read property 'onDidUpdateState' of undefined
### Stack Trace

Uncaught TypeError: Cannot read property 'onDidUpdateState' of undefined

```
At .atom\packages\copy-with-style\lib\atom_editor.js:58

TypeError: Cannot read property 'onDidUpdateState' of undefined
    at Editor.process_lines (/packages/copy-with-style/lib/atom_editor.js:58:70)
    at HTMLgenerator.generate (/packages/copy-with-style/lib/html_generator.js:58:45)
    at Object.copy (/packages/copy-with-style/lib/main.js:58:68)
    at HTMLElement.copyWithStylePreset1 (/packages/copy-with-style/lib/main.js:19:45)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.31.1/resources/app/src/command-registry.js:384:49)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/command-palette/lib/command-palette-view.js:152:35)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/atom-select-list/src/select-list-view.js:413:26)
    at HTMLDivElement.core:confirm (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/atom-select-list/src/select-list-view.js:118:20)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.31.1/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.31.1/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:16.6.0 command-palette:toggle (input.hidden-input)
     -0:13.7.0 core:confirm (input.hidden-input)
     -0:13.7.0 copy-with-style:preset1 (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.16 
auto-save-on-idle 1.2.1 
copy-with-style 1.1.0 
firacode 0.3.0 
formatter-clangformat 1.0.1 
gpp-compiler 3.0.7 
```

### LINKED ISSUE #15: Uncaught TypeError: Cannot read property 'buffer' of undefined
[Enter steps to reproduce:]

1. Open any file type
2. select text
3. press alt+a 1

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: [copy-with-style](https://github.com/my-codeworks/copy-with-style) package 1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of undefined

```
At /Users/bakerjames/.atom/packages/copy-with-style/lib/atom_editor.js:21

TypeError: Cannot read property 'buffer' of undefined
    at /packages/copy-with-style/lib/atom_editor.js:21:41)
    at HTMLgenerator.generate (/packages/copy-with-style/lib/html_generator.js:58:5)
    at Object.copy (/packages/copy-with-style/lib/main.js:58:68)
    at HTMLElement.copyWithStylePreset1 (/packages/copy-with-style/lib/main.js:19:45)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350017)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1212945)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209079)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285196)
```

### Commands

```
     -6:40 copy-with-style:copy (atom-text-editor.editor.is-focused.has-selection)
 25x -6:20.4.0 core:backspace (input.hidden-input)
     -5:14.7.0 editor:consolidate-selections (input.hidden-input)
     -5:14.7.0 core:cancel (input.hidden-input)
     -5:10.4.0 core:backspace (input.hidden-input)
     -4:47.9.0 core:select-all (input.hidden-input)
     -4:33.7.0 core:backspace (input.hidden-input)
     -4:01.3.0 core:copy (atom-text-editor.editor.is-focused.has-selection)
     -3:30.7.0 copy-with-style:copy (atom-text-editor.editor.is-focused.has-selection)
  2x -0:36 copy-with-style:preset1 (atom-text-editor.editor.is-focused.has-selection)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
copy-with-style 1.1.0 
language-gitignore 0.3.0 
language-latex 1.2.0 
markdown-pdf 2.2.0 
minimap 4.29.9 
pdf-view 0.71.0 
```

### PR DESCRIPTION
**Pull request by johnsbrew**
Hi, I've just upgraded your nice piece of work to the current Atom API (no more component.presenter)
- Fix #8, Fix #15, Fix #13, Fix #6
- Add new a feature: line numbering (HTML only for now)

@d-Pixie It seems you are not really caring about this package anymore but I saw you are still active on github. I guess you've switched to another editor ?

This PR is not exactly ready to be released, however before making it production ready I would like to know if:
- you are still interested in maintaining this repo & corresponding atom package ?
- you would like to transfer the ownership of this repo and of the corresponding atom to myself ?
- or if you would prefer me to fork away from the repo and create a new atom package from the fork ?

Just let me now :)

### CODE REVIEW

**Review by pokui — APPROVED** [review]
Tested and fixes said issues for me.

**Comment by johnsbrew** [comment]
Hi @pokui,
Thank you for your feedback.
I've been using this feature flawlessly for a couple presentation now.
FYI however there is a minor issue to fix: it currently does not work when all the buffer fits on the screen (very small buffers).
I had almost forgotten this PR, is there anyone interested in maintaining this package anymore?
Given the high latency on this PR I would consider to fork with a new atom package name if I was going to spend more time on this code.

**Comment by mlenkeit** [comment]
@johnsbrew thanks for sharing this PR, this was very useful!

👍 for merging this PR or creating a new package.

**Comment by newlukai** [comment]
Would be great to have this merged.

**Comment by mmarras** [comment]
@johnsbrew did you end up putting this under a new name, if so which one?

**Comment by eggrollofchaos** [comment]
Any update?

**Pull request merged**
